name: JSON Validator

on:
  # So that PRs touching the same files as the push are updated
    push:
        branches: [ main ]
    # So that the `dirtyLabel` is removed if conflicts are resolve
    # We recommend `pull_request_target` so that github secrets are available.
    # In `pull_request` we wouldn't be able to change labels of fork PRs
    pull_request_target:
        types: [ opened, synchronize ]

# Taken from https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/blob/8a192615582ce2002c0ce1dccfe2883164bb033d/.github/workflows/main.yml
jobs:
  Validatejson:
    name: Validate json
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint constants
        run: |
          #!/bin/bash
          echo "Linting contants..."
          for filename in constants/*.json; do
            if ! python -mjson.tool "$filename" &> /dev/null ; then
                echo "Linting $filename failed:"
                python -mjson.tool "$filename" > /dev/null
            fi
          done
          echo "Linted."